### ISSUE TITLE
skin helper service migration issues

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/skin.titan#133] opened 2015-09-02 06:37 UTC
here is a zip that contains the log file of the migration

and a couple mp4 video files that show after the migration a netflix home tile and a few other "blank" home times that I can't remove that appeared after the migration.

also some odd behavior with the weather fanart - cycles really fast.

https://onedrive.live.com/redir?resid=599DA6BD82779E65!4824&authkey=!AKVTPaSYQX_TqlA&ithint=file%2czip

the zip also contains a backup my skinshortcuts and guisettings before migration

**Comment by mgonzales71** [comment] 2015-09-02 06:58
forced views was on pre-migration after it was off and all the defined forced views were lost

after migration these are the only forced views you can pick:

![2015-09-01_23-47-16](https://cloud.githubusercontent.com/assets/6510026/9624696/f3bffb74-5103-11e5-96d0-aff9b9b0e876.png)

I checked and all views are "enabled" in settings

the "auto show OSD infopanel" was not defined/set - previously I had it set to 8 seconds

busy animation was not set/defined in settings after migration

the titan tiles setting pre migration was set to 1, after it was set to 2

the defined submenu as widgets were lost after migration

the weather widget was not working after migration

the system info widget was not working after migration

i am now going to try to re-define / setup the widgets again,,

**Comment by mgonzales71** [comment] 2015-09-02 07:07
redefining the widgets in the shortcut editor fixed all the widget issues.

still can't get rid of these extra home tiles (netflix + 5 mystery tiles)

**Comment by mgonzales71** [comment] 2015-09-02 07:10
here is a zip of my skin shortcuts post migration 
https://onedrive.live.com/redir?resid=599DA6BD82779E65!4826&authkey=!ALEOe0UErc5y7KU&ithint=file%2czip

**Comment by mgonzales71** [comment] 2015-09-02 07:12
and my guisettings post migration
https://onedrive.live.com/redir?resid=599DA6BD82779E65!4827&authkey=!AN1rJntcn7BY448&ithint=file%2cxml

**Comment by mgonzales71** [comment] 2015-09-02 07:15
hope all of this helps..
if you can - tell me how to remove the netflix and 5 mystery home tiles :) thanks!

**Comment by mgonzales71** [comment] 2015-09-02 07:45
hitting enter on this control in weather widget:

![2015-09-02_00-39-57](https://cloud.githubusercontent.com/assets/6510026/9625522/aa3bcebc-510b-11e5-8d50-b897e27348a9.png)

takes you here:

![2015-09-02_00-40-29](https://cloud.githubusercontent.com/assets/6510026/9625525/ac95c3d4-510b-11e5-8f59-7d810fb358b1.png)

**Comment by mgonzales71** [comment] 2015-09-02 07:55
the behavior of bringing you to the shortcut editor seems to happen when you don't have a 2nd widget defined

**Comment by mgonzales71** [comment] 2015-09-02 09:36
also here is a log file of a routine startup after migration - cleaned up widgets (redefined) but see several errors from skin helper service

https://onedrive.live.com/redir?resid=599DA6BD82779E65!4828&authkey=!AOwm_ekQ9gXdGb4&ithint=file%2clog

**Comment by mgonzales71** [comment] 2015-09-02 12:56
![2015-09-02_05-53-52](https://cloud.githubusercontent.com/assets/6510026/9631643/4a83453c-5137-11e5-8baf-c9c9e841bf64.png)

no effect / doesn't work (is it even needed anymore? since option in settings sets it?)

**Comment by mgonzales71** [comment] 2015-09-02 12:59
should the color picker have a	<include>DialogOverlayExtra</include>
or a panel behind it for better readability?

![2015-09-02_05-51-20](https://cloud.githubusercontent.com/assets/6510026/9631669/6cc3b5e6-5137-11e5-8545-bb4821caae8e.png)

**Comment by marcelveldt** [comment] 2015-09-02 18:31
Hi Mario, thanks a lot for testing the migration!
I will look into the issues tomorrow and try to fix them.

BTW: color picker is not yet finished, have to fix some stuff since the new skinhelper service.

**Comment by mgonzales71** [comment] 2015-09-02 20:26
You're welcome - been testing all I can think to test

Question - I have the netflix and what appears to be 5 mb3 home tiles that I can't delete.

how do I manually remove home tiles?

other then the issues in the above posts - haven't had any problems.

Even went so far as to disable/remove the old titanskin helpers script

will let you know if I find anything else

Thanks!

PS -

have you thought of maybe doing the migration differently?

say - create a home tile called "migrate" or a prompt at startup (until user migrates) that will download and install the new skin helper (kodi will prompt to download and install a missing addon when it's called) and then call the migration script.. then you could provide info about the migration, progress, report after it has run etc?

**Comment by marcelveldt** [comment] 2015-09-03 09:51
OK, I have fixed all issues you described.
Would it be possible for you to try the migration again ?
Just get latest version of the skin, skinhelper-script and the titan skin helper.
All three need to be updated.

The behaviour you described about the edit shortcuts screen beiing opened when you click the toggle widget button is by design. I have set that up so that users can easily define their 2nd widget.
This is to be replaced by a directly dialog to choose the widget for the shortcut but that isn't finished yet.

All migration issues should be covered now. Very interested in your testresults.

**Comment by mgonzales71** [comment] 2015-09-03 10:48
ok - going to roll back the changes, grab latest copies and try migration again..

will update soon with results - thanks!

**Comment by marcelveldt** [comment] 2015-09-03 10:58
OK, thanks! I'm very curious about the testresults

**Comment by mgonzales71** [comment] 2015-09-03 11:34
widget for my "programs" home tile did not migrate (was use submenu as widget)

the search action in shortcuts editor under /video library doesn't do anything now.

the home tile migrated still refering to titanskin helper - tried to redefine in new skin - as mentioned above - not function

everything else seemed to migrate fine.

here are some log file: one is of the migration and then the other is a log of a startup / shutdown of Kodi

https://onedrive.live.com/redir?resid=599DA6BD82779E65!4831&authkey=!AFP7voIfGUSH0mk&ithint=folder%2clog

it is safe to remove the titanskin helper now?

did you see the draft fanart and icons for the new skin helper service? (opened an issue on git to let you view, give feedback/discuss, etc.

this 2nd migration went a alot smoother!  

great work marcel!  :smile:

-Mario

**Comment by marcelveldt** [comment] 2015-09-04 22:14
1) All issues are now fixed on Git.
2) No, you still need the titan helper for now as it also needed to convert any colorthemes or skinbackups to the new values
3) Yeah, I saw the icons. Will grab tgem and see what it looks like, thanks!


Thanls for testing Mario!

**Closed by marcelveldt** 2015-09-04 22:14 UTC
