### ISSUE TITLE
Weather icons

### ISSUE THREAD

**Issue by vdb86** [marcelveldt/skin.titan#181] opened 2016-02-14 12:22 UTC
Not sure if this is a bug, when selecting weather icons, if the skin default ones are selected there is no weather icon, the other two work just fine.
Is the skin default option supposed to be no icon?
I like the option not to have an icon, just wanted to check if this is expected behavior or a bug.

**Comment by mgonzales71** [comment] 2016-02-14 12:39
what version of Kodi,  OS and Skin Version in use?
do you see anything in the logs (best if debug is enabled)
I have personally seen an issue with no weather icons trying to use beta skin for javis with some code from Isengard improperly merged (was my mistake) there were errors in the log file that helped me quickly figure that was the issue.

first - try to re-install the the skin from zip or repo.  If you still have the issue do a restart of Kodi with debug enabled.

Then upload the log to pastebin.com and share the link here.

FYI - Javis uses http://mirrors.kodi.tv/addons/jarvis/script.image.resource.select/ 
the Jarvis version of the skin requires:
<import addon="resource.images.weathericons.outline" version="0.0.4" optional="true"/>
<import addon="resource.images.weatherfanart.single" version="0.0.4" optional="true"/>
make sure they are all installed.

if you just drop the uncompressed zip of the skin in the addon dir they will not be automatically installed and could lead to the issue you are having.

Glad you are embracing Titan :smile: 

Mario

**Comment by vdb86** [comment] 2016-02-14 12:48
Alright I'll check all of this when I get a chance :smile: 
Btw installed this beta version of the skin from the emby repository.
Kodi version is Jarvis RC3.
Windows 7 64 bit.
Skin beta version 3.6.26 (Although I noticed this with previous version too).
Although this happens with the stable version of the skin too.
I'll follow up later on, got to get out of the house and take care of some things :smile:

**Comment by mgonzales71** [comment] 2016-02-14 13:03
ok - take your time.  follow up when you can :)

FYI - some weather icon sets I created for Jarvis - not yet posted / released them but feel free to check them out, use, etc.

here are the preview of the icons from the respective git repos

https://github.com/mgonzales71/resource.images.weathericons.met-shadow/blob/master/preview.jpeg
https://github.com/mgonzales71/resource.images.weathericons.linear_white/blob/master/preview.jpg
https://github.com/mgonzales71/resource.images.weathericons.linear_white2/blob/master/preview.jpeg

have a few others in addition to those - yea, I got bored one weekend hehe

**Comment by mgonzales71** [comment] 2016-02-14 13:07
a weather icon set I haven't yet sorted out and created an image resource for:
![untitled](https://cloud.githubusercontent.com/assets/6510026/13033810/a448018e-d2d8-11e5-8bc6-b7315ecf3599.png)

**Comment by marcelveldt** [comment] 2016-02-14 17:20
@vdb86 I think what you mean with the missing weather icons and fanart.
The skin has them included in the skin's addon.xml as optional required elementens but it seems that the optional tag is not working as I suspected and they're not installed by default. You will have to select them manually from the skin settings.

I do not want the skin cluttered with all kinds or required addons (because the user can not disable or remove them) so I'll remove them from the addon.xml for now untill I figure out a proper way to suggest the user to install an icon set

**Comment by vdb86** [comment] 2016-02-14 21:35
I think you're right, they haven't been installed.
I'm definitely missing:
resource.images.weathericons.outline
resource.images.weatherfanart.single

So I agree, it seems that the optional tag is not working.
**Btw I completely support your way of doing things, having optional stuff gives users a lot of space to do whatever they want instead of being forced to have add-ons installed.**

@mgonzales71 I like the first three ones!
The last one is ok, I feel that the other ones are better (but that's just my opinion)

I had some stuff going on and couldn't focus on Titan as I planed originally, but when I got to it I was just amazed.
Everything you said was completely true (and more), right away I understood why you wanted to work with Marcel.
If Titan skin was a community I would be happy to say that I'm a part of it.

**Comment by vdb86** [comment] 2016-02-14 21:37
@marcelveldt Mimic has a list of add-ons in settings which shows which add-ons are supported by the skin and their status (installed or not).

**Comment by marcelveldt** [comment] 2016-02-14 22:13
Yeah, I saw that... I did pretty much the same in Titan but instead of showing a list of addons I just show the actual feature they represent.

For example if you try to enable the skin setting "play tv tunes while browsing library" it will open tv tunes settings but if you don't have that installed it will ask you if you want it installed.

**Comment by vdb86** [comment] 2016-02-14 23:37
Sounds good and it makes sense.
Some users might find it easier to figure out what's missing if they had a separate section in options with a list of add-ons which could contain their explanations, that's definitely centralized then.
To me both ways work just fine.

**Comment by mgonzales71** [comment] 2016-02-15 02:49
Glad you love the skin as much as I do :)

Also glad your weather icon issue is resolved.

Enjoy the icons I should message Ronnie to see if he wants to place them in the main repo or not.

@Marcel,

Is the resource script included by default in Jarvis?  I am not at a computer to check - it's probably not the issue with the resources not being installed (being a prerequisite) but was a thought I had

**Comment by mgonzales71** [comment] 2016-02-15 06:10
regarding the comment on mimic and it's skin settings panel with supported addon status (and option to install those not yet installed)..

I actually saw that on Friday when I looking at the state of other skins as we approach Jarvis release to see what was new, etc.

I was thinking that this could be useful for Titan - thoughts Marcel?

That Auto Complete looks intruiging - I am going to look into what that is/does (well besides the obvious hehe)

screenshot:

![2016-02-14_22-03-15](https://cloud.githubusercontent.com/assets/6510026/13040949/706b967a-d367-11e5-8851-324a4c56f823.png)

**Comment by vdb86** [comment] 2016-02-15 09:18
Auto complete looks interesting but in real world scenario I feel that very few people will be using it.
That feature would make sense if Kodi had a web browser or something like that.
Right now users don't write that many things that they would need auto complete, but I might be wrong, this is just from personal experience.

**Comment by mgonzales71** [comment] 2016-02-15 10:12
Web browser support is actually on the roadmap.  

Personally I think that a basic WebKit based browser / HTML render engine is long overdue for Kodi.

**Comment by mgonzales71** [comment] 2016-02-15 10:19
Ok but you may have miss some benefits of this panel.

Here is an example:

To configure a service like next up notifications you have to go to addons - system - running, find the service, context menu, choose configure 

This panel lists the skin supported addons
Shows you the current version if installed
Click to install
Once installed - click to configure 
Great time saver and support tool in my opinion.

Just thinking out loud - I'll let you be the judge on this since I know how to configure install etc no problem :)

**Comment by vdb86** [comment] 2016-02-15 11:44
Regarding web browser, both OE and OSMC announced a web browser more than 6 months ago.
But somewhat later they put it aside.
OE guys - since part of their team had to step back from development
OSMC guys - I guess they focused on their new hardware (Vero 2) which is out now

I don't think Kodi guys will be making a web browser, at this point they can't handle the development of Kodi itself and user support, they are already over saturated and are missing emails/messages from developers and bug reports on bug tracker, let alone ordinary users.

But yes, a browser is long overdue!

**Comment by mgonzales71** [comment] 2016-02-15 11:59
Although it hasn't been assigned a milestone yet it is planned

See: HTML Layout Engine at the end of this roadmap page.

http://trac.kodi.tv/roadmap?show=all

It's also been discussed on the forums and in a blog post as a top feature the Kodi team wants to implement - most likely the G* milestone.

WebKit is really well documented and has great APIs so it's not unachievable 

Here's to hoping it happens :)

Mario

**Comment by marcelveldt** [comment] 2016-02-15 18:40
Sure I can add that extra page with addons. One minor detail will be that it means the left menu in the skin settings will go scrolling as that additional option isn't going to fit :-)

**Comment by vdb86** [comment] 2016-02-15 18:45
Well since you implemented the best options and quite a few of them I think everyone will understand why it's scrolling :D

**Comment by marcelveldt** [comment] 2016-02-15 19:18
I implemented that addition addons page in skin settings.

The autocompletion was part of extendedinfo but now a seperate addon that can be used inside the virtual keyboard to auto complete any entries.

Might be something to implem,ent, isn't that much work at all

**Comment by mgonzales71** [comment] 2016-02-21 01:37
you saw the duplicate of cinemavision right?
maybe add - script.trakt?

you may have just done this - just saw a new update on GIT.  going to look  now.

btw Kodi 16 Javis final is on mirrors.kodi.tv today but not yet announced.

**Comment by smvicente** [comment] 2016-05-04 02:28
Hi! I love your Skin, but after downgrade from the 16.1 version to the 15.2 (doing a clean reinstall but loading previous settings), I'm not able to select an icon pack for the Weather as before.

I have tried adding manually the mentioned resources and editing several XML files without luck :(

Is there any workaround for this?

Thank you in advance and thank you for your work!

**Comment by marcelveldt** [comment] 2016-05-04 06:04
@smvicente 
next time please report any issues on the forums as that is easier for me to track.

The skin settings of theKodi Jarvis version of the skin are not 100% compatible with the Isengard version, but you found out already ;-)

You will have to manually change your kodi settings file to fix this one:

1. Close down Kodi
2. Open the file guisettings.xml (in kodi userdata folder) in a texteditor
3. Remove all references to WeatherIconPack

**Comment by smvicente** [comment] 2016-05-04 10:35
Thank you and sorry!!

**Closed** 2016-10-07 20:59 UTC
