### ISSUE TITLE
Home menu Music item missing

### ISSUE THREAD

**Issue by vdb86** [marcelveldt/skin.titan#188] opened 2016-02-23 11:39 UTC
Hi Marcel, I've noticed that the Music item is missing in Home menu if I don't have any music scanned to my music library.
It should be visible but it's not, so basically in order to add music to the library I ave to change the skin to confluence, add it and then get back.
The same issue is present in Mimic, so I guess skin shortcuts or whichever add-on is used to create the Home menu is probably the culprit.

**Comment by marcelveldt** [comment] 2016-02-23 19:30
Yep, this was once like that by design (when Kodi had a different view for music files and library) but since these are merged in Jarvis it has become a bug ;-)

Will be fixed shortly

**Comment by vdb86** [comment] 2016-02-23 19:34
Sounds good!

**Comment by marcelveldt** [comment] 2016-02-24 14:07
This is now fixed in skinshortcuts. A new release of skinshortcuts will be released later today. For the time beiing I placed a temp beta version on the beta repo for the skin.

**Comment by vdb86** [comment] 2016-02-24 14:08
Awesome!

**Closed by marcelveldt** 2016-02-24 14:07 UTC
